---
abstract: 'Easy installation of the Saleae Logic SDK'
author:
  - 'Vikas N Kumar <vikas@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Alien::Base: 0
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-SaleaeLogic
provides:
  Alien::SaleaeLogic:
    file: lib/Alien/SaleaeLogic.pm
    version: 0.01
requires:
  Alien::Base: 0
  File::ShareDir: 1.00
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
